[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.46.0",
    "google-generativeai>=0.8.5",
    "packaging>=25.0",
]
